# Generated by Django 5.1.3 on 2024-12-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('content', models.TextField(blank=True, verbose_name='текст')),
                ('rating', models.CharField(choices=[('Отлично!', 'Отлично!'), ('Очень хорошо', 'Очень хорошо'), ('Хорошо', 'Хорошо'), ('Плохо', 'Плохо'), ('Очень плохо', 'Очень плохо')], default='Отлично!', max_length=15, verbose_name='оценка')),
                ('published', models.BooleanField(default=True, verbose_name='опубликован')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-time_create', 'title'],
            },
        ),
    ]
